### ISSUE TITLE
Offer a shim for prompt(), alert(), confirm()

### ISSUE THREAD

**Issue by frank-dspeed** [nwjs/nw.js#7764]
Chromium wants to deprecate: prompt(), alert(), confirm()

from the window context I am working on a migration path that works on the web via shiming that functions as also nwjs 

## Todo
- [ ] Create The Functions with similar behavior 
- [ ] Design common layout for the functions
- [ ] create a function to apply this functions to iframes as requested by https://github.com/nwjs/nw.js/issues/7763

```js
const alert = (msg) => {
  //  showMessage
  //  while Message is there loop.
  // void;
}
const confirm = (msg) => { 
  // showMessage 
  // loop while no Answer
  // return boolean
}

const prompt = (question, answer) => {
  // Show Prompt
  // while loop while no Answer 
  // return string or null
}
```

we need to verify that we can process user input maybe via a popup. i expect that changing loop conditions via a outside process works. but it needs verification if that does not work we do not need to implement it.

It should only get implemented in a way that is still Web Compatible.

While any one that is using this should simply refactor his code to use promises.

## Alternativ
use rollup or a other loader to transpil all js files this has a complex matrix of conditions but i think it is do able
we would need user samples of real code to do that.
clean migration would be to replace alert() confirm, prompt with promises
```js
alert() => promise<void>
confirm() => promise<boollean>
prompt() => promise<string|null>
```

code like

```js
alert('hi')
// more code after that
```

would get 
```js
alert('hi').then(()=>{
  // More code after that
})
```

```js
var doIt = window.confirm('Really?');
if (doIt) {

}
// more code
```
gets
```js
var doIt = window.confirm('Really?');
doIt.then( really => {
  if (really) {

  }
  // more code
})
```

```js
var yourName = window.prompt('yourName', 'foo?');
if (yourName === null) {
  // canceld
}

if (yourName) {
  // none Empty String '' is also false
}

// more code
```
gets
```js
var $yourName = window.prompt('yourName', 'foo?');
$yourName.then( yourNamel => {
  if (yourName === null) {
    // canceld
  }
  
  if (yourName) {
    // none Empty String '' is also false
  }

  // more code
})
```

rollup could do such complex wrapping but it is some effort

most problematic part is when alert gets assigned to a variable or something or if you access it on diffrent context
like window.alert and myWindow.alert i do not expect that any one has done that but i have no data. some one would need to verify that using googles http archive project.

Also none solved is what happens if some one abused setTimeout in such a scenario request animation frame is also possible while most people that use that old behavior will have not used requestAnimationFrame as it has not existed in that time.

algo:

```
const userInput = alert | prompt | confirm
 // get imports
 // parse imports for userInput usage add metadata to resolve hook
 // wrapp alert usage on bundle level scope the wrapper around every code following inside same scope
 
```

## Update

```js
(async () => {
  var yourName = await window.prompt('yourName', 'foo?');
  if (yourName === null) {
    // canceld
  }
  
  if (yourName) {
    // none Empty String '' is also false
  }
  
  // more code
})()
```

is maybe even more clean. and would make the scope thing more clear.

## complex scenario

```js
 document.querySelector('#button').addEventListener('click',warnung);
  
  
  function warnung() {
    alert('Sie sollten doch nicht drücken!');
  }
```

```js
 document.querySelector('#button').addEventListener('click', warnung);
  
  // we can asume that this does not rellay on stop the world
  // if so we simply accept it wont-fix
  async function warnung() {
    await alert('Sie sollten doch nicht drücken!');
  }

```

Closes: #7763

**Comment by frank-dspeed** [comment]
so in most cases it is not so hard out of my view to update the existing code it needs only to get wrapped

**Comment by TheJaredWilcurt** [comment]
looks like they might be rolling it back

* https://www.theregister.com/2021/08/05/google_chrome_iframe/

**Comment by frank-dspeed** [comment]
@TheJaredWilcurt nope it is reverse origin trial so you get 6 month to prepare to migrate if you opt in

https://developer.chrome.com/origintrials/#/register_trial/2541156089743802369

**Comment by Jermolene** [comment]
Hi @frank-dspeed sadly those polyfills do not provide the same behaviour as the built-in alert/confirm/prompt. In particular, the native versions block JS execution so that (a) they don't return until the dialog is dismissed and (b) the event loop doesn't run until the dialog is dismissed. The semantic differences may seem like nitpicking but our usage of these functions relies on this well-documented Web platform behaviour.

**Comment by frank-dspeed** [comment]
@Jermolene i need a example out of my view as a ECMAScript Engine Implementor is that when the code is put in the right scope it will lead to the same behavior. I can not draw now all the situations but i have a clear view of that provide me a example that depends on that so that i see the full code that is needed to get it blocking.

**Comment by Jermolene** [comment]
> @Jermolene i need a example out of my view as a ECMAScript Engine Implementor is that when the code is put in the right scope it will lead to the same behavior. I can not draw now all the situations but i have a clear view of that provide me a example that depends on that so that i see the full code that is needed to get it blocking.

I don't know how to explain things better than I did above. The built-in alert/confirm/prompt dialogues pause JS execution while they are displayed, including blocking the event loop. As far as I can tell that behaviour is impossible to achieve in pure JS.

There are Stack Overflow answers  that cover this in more detail. For example: https://stackoverflow.com/questions/13635297/emulate-javascript-alert-blocking-nature

**Comment by frank-dspeed** [comment]
@Jermolene i understand that but your not really help full i still need a example i do not know how to explain it more simple but JS is using only a SIngle Process at the time so as soon as it does something async it will not execute anything else in the stack until that async action has finished 

so putting code into the right {} scope will prevent functions from running until that async action has finished 

please simply provide me with a example so that i can show you what i mean.

**Comment by Jermolene** [comment]
> @Jermolene i understand that but your not really help full

Apologies, I appreciate your engagement, and don't mean to be unhelpful.

> i still need a example i do not know how to explain it more simple but JS is using only a SIngle Process at the time so as soon as it does something async it will not execute anything else in the stack until that async action has finished
> 
> so putting code into the right {} scope will prevent functions from running until that async action has finished
> 
> please simply provide me with a example so that i can show you what i mean.

This ticket proposes making a pure JS shim that provides the functionality of prompt/alert/confirm. I tried above to show why that is impossible, and as secondary evidence I have pointed to the other discussions you can find on the web about this, including the Stack Overflow answer above.

I will try to extract a simple minimal test case, but our project is a complex web application and it's going to be a big job. Our usage of "confirm()" is deeply embedded within it but isn't anything special. It just requires the behaviour in the spec: that alert/confirm/prompt blocks all JS execution such as timer callbacks (what the spec calls tasks and microtasks):

https://html.spec.whatwg.org/#simple-dialogs

**Comment by Jermolene** [comment]
> please simply provide me with a example so that i can show you what i mean.
> 
> for example if you register a lot of eventHandlers that should not fireAnymore or setTimeout loops and all that i need to see the whole context to make assumptions in general i expect not much trouble.
> 
> most libs nowdays use syntetic events so they work with a patched event object already. i expect that all code that needs to get blocked can get blocked while displaying a modal

I only saw these additions after my reply.

This ticket proposes a shim for alert/confirm/prompt. If it also requires modifications to other code, then it isn't a drop-in-shim, instead it's a recipe for rewriting our application, which we're trying to avoid.

**Comment by frank-dspeed** [comment]
@Jermolene your application is not even a problem i discuess that with you and want to solve that with you for millions of people.

for your special drop in requirment usecase we can offer in nwjs a working alternativ using C when we call a C module via JS we get the blocking behavior while we are able to take user input.

**Comment by Jermolene** [comment]
> @Jermolene your application is not even a problem i discuess that with you and want to solve that with you for millions of people.
> 
> for your special drop in requirment usecase we can offer in nwjs a working alternativ using C when we call a C module via JS we get the blocking behavior while we are able to take user input.

Thanks @frank-dspeed I'm delighted that is possible, it sounds like it would resolve our problem.

**Comment by frank-dspeed** [comment]
@Jermolene i do not expect that some one codes that fast enough we have only one C coder that knows a bit about CEF. 

i only know that we need to implement it in C via the CefDialogHandler API.
